import * as THREE from 'three';
import {PLACES,restoreDiscoveries,createDetails} from './details.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {mergeGeometries} from './vendor/BufferGeometryUtils.js';
import {RADIUS as R,ROOF,STAIR,NEIGHBORS,BUILDINGS,fresh,restore,distance,brewOne,deliver,floorAt,advance,route} from './simulation.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),SAVE='okemori-coffee-animals-v1';
const comparison=new URLSearchParams(location.search).get('scene')==='cafe';
let state=fresh();try{if(!comparison)state=restore(localStorage.getItem(SAVE));}catch{}
if(comparison){state={...fresh(),cups:4};document.body.classList.add('comparison-scene');}
// Retain deliveries from the first prototype; relocate a saved roof position to the new walk.
if(!comparison&&state.h>4.5&&state.h<6){state.x=STAIR.x;state.z=STAIR.upperBack;state.h=ROOF;}
let ready=false,brewing=false,brewTimer=0,walking=[],guideName='',jump=0,jumpV=0,yaw=0,orbit=.48,zoom=10.4,overview=false,audio=null,sound=false,toastTimer=0,lastUi='',time=0,lastSave=0;
let details=null,discovered=new Set();try{if(!comparison)discovered=restoreDiscoveries(localStorage.getItem(SAVE+'-journal'));}catch{}
const keys=new Set(),models={},people=[],cups=[];
const scene=new THREE.Scene();scene.background=new THREE.Color('#e5ecd9');scene.fog=new THREE.Fog('#e5ecd9',65,145);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,250);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
scene.add(new THREE.HemisphereLight('#fff8e9','#b0b99f',1.85));const sun=new THREE.DirectionalLight('#fff3da',2.5);sun.position.set(-25,48,28);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-43;sun.shadow.camera.right=43;sun.shadow.camera.top=43;sun.shadow.camera.bottom=-43;sun.shadow.camera.far=140;sun.shadow.normalBias=.03;sun.shadow.bias=-.00012;scene.add(sun);
const up=new THREE.Vector3(0,1,0),v3=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
function at(x,z,h=0){const a=x/R,b=z/R;return v3(Math.sin(a)*Math.cos(b),Math.cos(a)*Math.cos(b),Math.sin(b)).multiplyScalar(R+h);}
function frame(x,z){const a=x/R,b=z/R;const east=v3(Math.cos(a),-Math.sin(a),0),normal=at(x,z).normalize(),south=v3(-Math.sin(a)*Math.sin(b),-Math.cos(a)*Math.sin(b),Math.cos(b));return new THREE.Matrix4().makeBasis(east,normal,south);}
function place(o,x,z,h=0,angle=0){o.position.copy(at(x,z,h));o.quaternion.setFromRotationMatrix(frame(x,z));if(angle)o.rotateY(angle);return o;}
const scenery=new THREE.Group();scene.add(scenery);
const materials={};function mat(color){return materials[color]||(materials[color]=new THREE.MeshStandardMaterial({color,roughness:.9}));}
function mesh(geo,color,parent=scenery){const o=new THREE.Mesh(geo,mat(color));o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
const planet=mesh(new THREE.SphereGeometry(R,96,64),'#abc28d',scene);planet.castShadow=false;
function tile(x,z,w,d,h,color,thick=.06){const o=mesh(new THREE.BoxGeometry(w,thick,d),color);place(o,x,z,h);return o;}
const roads=[[[0,3],[0,19],3.6],[[-17,5.5],[18,5.5],4.2],[[-14,5],[-14,12],2.4],[[14,5],[14,13],2.4],[[-11,6],[-11,-10],2.4],[[-11,-10],[-15,-10],2.4],[[7,6],[STAIR.x,STAIR.front],2],[[-8.7,3.6],[-3.5,3.6],3.2]];
function segmentDistance(x,z,a,b){const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz)));return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz);}
for(let ix=-46;ix<=46;ix++)for(let iz=-26;iz<=46;iz++){const x=ix*.44,z=iz*.44;if(!roads.some(([a,b,w])=>segmentDistance(x,z,a,b)<w/2))continue;tile(x,z,.45,.45,.015,'#e1ddcb',.026);const n=Math.sin(ix*127.1+iz*311.7)*43758.5453,r=n-Math.floor(n);if(r>.2){const stone=tile(x+(r-.5)*.04,z+(r-.5)*.035,.29+r*.09,.33+r*.065,.04+r*.009,r>.6?'#e7e3d0':'#e3dfcc',.027);stone.rotateY((r-.5)*.35);}}
// Repeatable scenery; handmade GLB assets remain independently editable.
let seed=41;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function tinyFlowers(x,z){const g=new THREE.Group();scenery.add(g);place(g,x,z,.05);for(let i=0;i<8;i++){const a=i*2.4,r=.12+(i%3)*.1,y=.19+(i%4)*.05;const xx=Math.cos(a)*r,zz=Math.sin(a)*r;const stem=mesh(new THREE.CylinderGeometry(.012,.015,y,5),'#718552',g);stem.position.set(xx,y/2,zz);for(let k=0;k<5;k++){const b=k*Math.PI*2/5;const petal=mesh(new THREE.SphereGeometry(.065,6,4),i%3===0?'#dbb4a6':i%3===1?'#ead191':'#f0e8ce',g);petal.scale.set(1,.45,.85);petal.position.set(xx+Math.cos(b)*.065,y,zz+Math.sin(b)*.065);}const center=mesh(new THREE.SphereGeometry(.029,6,4),'#c2a150',g);center.position.set(xx,y+.017,zz);const leaf=mesh(new THREE.SphereGeometry(.075,6,4),'#91a778',g);leaf.scale.set(1,.25,.6);leaf.position.set(xx+.04,y*.4,zz);}}
for(const [x,z]of [[-3.6,3],[-3.75,3.65],[-3.4,4.3],[3.05,4.3],[3.15,5],[-8.6,1.7],[-4.15,1],[-8.8,4],[-5.2,2.5],[6.3,1.5],[9.6,3.5],[10,4.1],[-14,11.5],[14.8,13],[2,16],[-2,15]])tinyFlowers(x,z);
for(let i=0;i<30;i++){let x=(rand()-.5)*42,z=(rand()-.2)*32;if(Math.abs(x)>11&&!(Math.abs(x-14)<2)&&!(Math.abs(x+14)<2))tinyFlowers(x,z);}
function lamp(x,z){const g=new THREE.Group();scenery.add(g);place(g,x,z);const p=mesh(new THREE.CylinderGeometry(.045,.06,2.7,8),'#485b4b',g);p.position.y=1.35;const lantern=mesh(new THREE.BoxGeometry(.34,.48,.34),'#ffe4a3',g);lantern.position.y=2.7;for(let a=0;a<4;a++){const q=mesh(new THREE.CylinderGeometry(.018,.018,.55,5),'#465642',g);q.position.set(a%2?.18:-.18,2.7,a<2?.18:-.18);}const roof=mesh(new THREE.ConeGeometry(.32,.22,4),'#475b48',g);roof.position.y=3.07;roof.rotation.y=Math.PI/4;}
for(const p of [[-4.7,5.8],[5.8,6.6],[-10,9],[11,13],[-11,-8],[3,15]])lamp(...p);
function bench(x,z,angle=0){const g=new THREE.Group();scenery.add(g);place(g,x,z,0,angle);for(let i=0;i<3;i++){let o=mesh(new THREE.BoxGeometry(1.65,.08,.14),'#af8354',g);o.position.set(0,.52,i*.19-.2);}for(let i=0;i<2;i++){let o=mesh(new THREE.BoxGeometry(1.65,.15,.07),'#bd955c',g);o.position.set(0,.85+i*.2,-.36);}for(const x of [-.64,.64]){const o=mesh(new THREE.BoxGeometry(.07,.85,.55),'#536451',g);o.position.set(x,.42,-.08);}}
bench(-15,-8);bench(-3,15,-.3);bench(12,12,.4);
const pond=mesh(new THREE.SphereGeometry(1,48,16),'#91b8af');pond.scale.set(3.6,.11,2.6);place(pond,0,22,.03);for(let i=0;i<24;i++){const a=i/24*Math.PI*2;const rock=mesh(new THREE.DodecahedronGeometry(.28+rand()*.17),'#c4c5ab');place(rock,Math.cos(a)*3.6,22+Math.sin(a)*2.65,.13);rock.scale.y=.55;}
// Two flights keep the lower garden landing and upper footbridge distinct.
function stairFlight(front,back,base,height,count){for(let i=0;i<count;i++){const z=front-(i+.5)*(front-back)/count,h=base+height*(i+1)/count;tile(STAIR.x,z,STAIR.width,(front-back)/count+.015,h-.075,'#89a78d',.14);tile(STAIR.x,z+(front-back)/count*.42,STAIR.width+.02,.032,h+.006,'#d4b787',.023);}for(const x of [STAIR.x-.86,STAIR.x+.86]){const points=[];for(let i=0;i<=count;i++){const z=front-i*(front-back)/count,h=base+height*i/count;points.push(at(x,z,h+.78));if(i%3===0){const post=mesh(new THREE.CylinderGeometry(.024,.024,.8,6),'#3d5545');place(post,x,z,h+.4);}}mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),64,.037,6,false),'#916a43');}}
stairFlight(STAIR.front,STAIR.back,0,STAIR.landing,30);stairFlight(STAIR.back,STAIR.upperBack,STAIR.landing,ROOF-STAIR.landing,18);
function footbridge(ax,az,bx,bz){const len=Math.hypot(bx-ax,bz-az),count=Math.ceil(len/.3),angle=Math.atan2(bx-ax,bz-az);for(let i=0;i<=count;i++){const t=i/count,x=ax+(bx-ax)*t,z=az+(bz-az)*t;const plank=tile(x,z,1.6,.31,ROOF-.04,'#b9a37f',.12);plank.rotateY(angle);for(const side of [-1,1]){const post=mesh(new THREE.CylinderGeometry(.018,.018,.84,6),'#354b3d');place(post,x+Math.cos(angle)*side*.77,z-Math.sin(angle)*side*.77,ROOF+.42);}}for(const side of [-1,1])for(const h of [ROOF+.19,ROOF+.88]){const points=[];for(let i=0;i<=count;i++){const t=i/count;points.push(at(ax+(bx-ax)*t+Math.cos(angle)*side*.77,az+(bz-az)*t-Math.sin(angle)*side*.77,h));}mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),count*2,.03,6,false),'#354b3d');}}
footbridge(-6.5,-.4,7.2,-.4);footbridge(-6.5,STAIR.upperBack,7.2,STAIR.upperBack);footbridge(-6.5,STAIR.upperBack,-6.5,.5);footbridge(7.2,STAIR.upperBack,7.2,1.5);
const gardenArch=new THREE.Group();scenery.add(gardenArch);place(gardenArch,STAIR.x,STAIR.back,STAIR.landing);for(const x of [-.75,.75]){const post=mesh(new THREE.CylinderGeometry(.12,.14,1.3,8),'#7d9e75',gardenArch);post.position.set(x,.65,0);}for(let i=0;i<=12;i++){const a=i*Math.PI/12;const leaf=mesh(new THREE.IcosahedronGeometry(.19,1),'#94ad80',gardenArch);leaf.position.set(Math.cos(a)*.75,1.3+Math.sin(a)*.75,0);}const archSign=mesh(new THREE.BoxGeometry(.87,.3,.07),'#efe8ce',gardenArch);archSign.position.set(0,1.54,.1);

function forestSign(text,x,z,h,w=2.6){const c=document.createElement('canvas');c.width=768;c.height=168;const ctx=c.getContext('2d');ctx.fillStyle='#f3ead2';ctx.fillRect(0,0,768,168);ctx.strokeStyle='#79936b';ctx.lineWidth=6;ctx.strokeRect(12,12,744,144);ctx.fillStyle='#3c5844';ctx.font='600 66px serif';ctx.textAlign='center';ctx.fillText(text,384,108);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Mesh(new THREE.PlaneGeometry(w,w*168/768),new THREE.MeshStandardMaterial({map:tex,roughness:1}));scenery.add(sign);place(sign,x,z,h);}
forestSign('MORI COFFEE',0,-1.32,2.96,3.6);
for(const [x,z]of [[-4,6.8],[-9,15],[4.7,14],[-6.3,19],[11,14],[-17,-6]]){const g=new THREE.Group();scenery.add(g);place(g,x,z);for(let i=0;i<3;i++){const stalk=mesh(new THREE.CylinderGeometry(.04,.06,.22,8),'#eee0c2',g);stalk.position.set(i*.18,.11,Math.sin(i)*.15);const cap=mesh(new THREE.SphereGeometry(.16,12,8,0,Math.PI*2,0,Math.PI/2),'#bd8063',g);cap.position.set(i*.18,.22,Math.sin(i)*.15);cap.scale.y=.7;for(let j=0;j<3;j++){const dot=mesh(new THREE.SphereGeometry(.024,6,4),'#f5e4c8',g);dot.position.set(i*.18+Math.cos(j*2.1)*.07,.3,Math.sin(i)*.15+Math.sin(j*2.1)*.07);}}}

const courier=new THREE.Group();scene.add(courier);const body=new THREE.Group();courier.add(body);const footsteps=[];
function optimizeStatic(root){const buckets=new Map();root.updateMatrixWorld(true);root.traverse(o=>{if(!o.isMesh||Array.isArray(o.material))return;const key=o.material.uuid+'|'+Object.keys(o.geometry.attributes).sort().join(',')+'|'+!!o.geometry.index;if(!buckets.has(key))buckets.set(key,{mat:o.material,geos:[]});const geo=o.geometry.clone();geo.applyMatrix4(o.matrixWorld);buckets.get(key).geos.push(geo);});const g=new THREE.Group();for(const b of buckets.values()){const geo=mergeGeometries(b.geos);if(geo){const m=new THREE.Mesh(geo,b.mat);m.castShadow=true;m.receiveShadow=true;g.add(m);}for(const geo of b.geos)geo.dispose();}return g;}
async function load(){const loader=new GLTFLoader();let count=0;for(const name of ['cafe','capybara','leaf','florist','studio','bookshop','bakery','tree',...NEIGHBORS.map(n=>n.species)]){const gltf=await loader.loadAsync(`assets/${name}.glb`);models[name]=(name==='capybara'||NEIGHBORS.some(n=>n.species===name))?gltf.scene:optimizeStatic(gltf.scene);$('loading-message').textContent=`森の支度 ${++count} / 16`; }const cafe=models.cafe.clone();scenery.add(cafe);place(cafe,0,0,.02);body.add(models.capybara);models.capybara.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}if(/^Cup_[1-4]$/.test(o.name))cups.push(o);if(/^foot_[LR]$/.test(o.name))footsteps.push({o,y:o.position.y});});
cups.sort((a,b)=>b.name.localeCompare(a.name));
for(const b of BUILDINGS){const o=models[b.type].clone();scenery.add(o);place(o,b.x,b.z);}
for(let i=0;i<85;i++){let x=(rand()-.5)*Math.PI*R*2,z=(rand()-.5)*62;if(Math.abs(x)<23&&z> -17&&z<27)continue;const o=models.tree.clone();scenery.add(o);place(o,x,z,-.05);o.scale.setScalar(.65+rand()*.55);}
for(const p of [[-22,8],[-20,-4],[15,-8],[19,-16],[22,2],[-7,20],[-7,-13],[15,23],[8,29],[-9,16],[7,13],[-19,15],[21,16],[-4,27],[5,29],[-20,-12],[15,-15]]){const o=models.tree.clone();scenery.add(o);place(o,...p);}
const bakedScenery=optimizeStatic(scenery);scene.remove(scenery);scene.add(bakedScenery);
for(const n of NEIGHBORS){const pivot=new THREE.Group(),model=models[n.species].clone(true);pivot.add(model);scene.add(pivot);place(pivot,n.x,n.z,n.h);model.scale.setScalar(.92);model.traverse(o=>{if(/^Cup_/.test(o.name)||o.name.toLowerCase().startsWith('tray'))o.visible=false;if(o.isMesh&&o.material.name==='blue'){o.material=o.material.clone();o.material.color.set(n.color);}});const ring=mesh(new THREE.TorusGeometry(.63,.027,6,40),'#ebd294',pivot);ring.rotation.x=Math.PI/2;ring.position.y=.045;const gift=models.capybara.getObjectByName('Cup_1').clone(true);gift.position.set(0,.79,.41);gift.visible=false;model.add(gift);people.push({n,pivot,model,ring,gift,celebrate:0});}
details=createDetails({THREE,scene,place,mat});updateJournal();ready=true;$('loading').classList.add('done');setTimeout(()=>$('loading').hidden=true,800);if(state.delivered.length||state.cups)$('welcome').hidden=true;updateUI();renderFrame(0);}
function save(){if(comparison)return;try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{$('save-status').textContent='保存できないため、この画面を開いている間だけ続けられます。';}}
function toast(who,what){$('speaker').textContent=who;$('message').textContent=what;$('speech').classList.add('show');toastTimer=5;}
function chime(note=523,duration=.25){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=note;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.07,audio.currentTime+.025);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function closeWelcome(){$('welcome').hidden=true;}
function nearby(){return NEIGHBORS.find(n=>distance(state,n)<2.3&&!state.delivered.includes(n.id));}
function nearbyPlace(){return PLACES.find(p=>distance(state,p)<2.05);}
function action(){if(!ready||brewing)return;closeWelcome();const n=nearby();if(n){if(!state.cups){toast(n.name,'カフェで、コーヒーを淹れてきてね。');return;}if(deliver(state,n.id)){const friend=people.find(p=>p.n.id===n.id);if(friend)friend.celebrate=2;toast(n.emoji+' '+n.name,n.line);chime(659);setTimeout(()=>chime(880),130);updateUI();save();if(state.delivered.length===8){walking=[];setTimeout(()=>$('finish').showModal(),900);}}return;}const point=nearbyPlace();if(point){details.trigger(point.id);discovered.add(point.id);if(!comparison)try{localStorage.setItem(SAVE+'-journal',JSON.stringify([...discovered]));}catch{}toast(point.title,point.memory);chime(point.id==='bell'?660:point.id==='pond'?280:440,.8);updateJournal();return;}if(distance(state,{x:0,z:3,h:0})<3){if(state.cups===4){toast('おけもんの森カフェ','トレイはいっぱい。いい朝を、届けにいこう。');return;}brewing=true;walking=[];brewTimer=0;toast('おけもんの森カフェ','一杯ずつ、ゆっくり淹れています。');updateUI();return;}toast('小さなヒント',state.cups?'近くの住人に、コーヒーを届けよう。':'カフェへ戻って、次の4杯を淹れよう。');}
function guide(destination,name){if(!ready||brewing)return;closeWelcome();walking=route(state,{...destination,x:destination.x+(destination.species?-1.15:0),z:destination.z+(destination.id?(destination.species?.9:destination.h>.1?.65:1.05):0)});guideName=name;overview=false;zoom=Math.min(zoom,20);toast('道案内',`${name}へ、歩いていこう。`);$('book').hidden=true;$('book-toggle').setAttribute('aria-expanded','false');updateUI();}
function nextGuide(){if(walking.length){walking=[];guideName='';updateUI();return;}if(!state.cups&&state.delivered.length<8){guide({x:0,z:3,h:0},'カフェ');return;}const n=NEIGHBORS.find(n=>!state.delivered.includes(n.id));if(n)guide(n,n.name);else toast('ひとやすみ','今日はみんなに届けたね。星を眺めてみよう。');}
for(const n of NEIGHBORS){const button=document.createElement('button');button.className='neighbor';button.id=`neighbor-${n.id}`;button.innerHTML=`<span class="avatar" style="--color:${n.color}"><img src="assets/portrait-${n.species}.png" alt=""></span><span class="name">${n.name}<small>${n.place}</small></span><span class="mark">○</span>`;button.onclick=()=>guide(n,n.name);$('neighbors').append(button);}
function updateUI(){const point=nearbyPlace(),n=nearby(),atCafe=distance(state,{x:0,z:3,h:0})<3;const signature=[state.cups,state.delivered.join(),n?.id,point?.id,atCafe,brewing,walking.length>0,overview].join('|');if(signature===lastUi)return;lastUi=signature;$('cups').textContent=state.cups;$('delivered').textContent=state.delivered.length;for(let i=0;i<cups.length;i++)cups[i].visible=i<state.cups;for(const n of NEIGHBORS){const done=state.delivered.includes(n.id),el=$(`neighbor-${n.id}`);el.classList.toggle('done',done);el.querySelector('.mark').textContent=done?'✓':'○';el.setAttribute('aria-label',`${n.name}・${n.place}へ道案内${done?'・配達済み':''}`);}for(const p of people){const done=state.delivered.includes(p.n.id);p.ring.visible=!done;p.gift.visible=done;p.model.traverse(o=>{if(/^arm_[LR]$/.test(o.name)){o.position.y=done?.74:.65;o.position.z=done?.24:.09;o.rotation.x=done?-.45:0;}});}$('interact').innerHTML=brewing?'☕ コーヒーを淹れています…':n?`☕ ${n.name}に渡す <kbd>E</kbd>`:point?`${point.action} <kbd>E</kbd>`:atCafe?'☕ コーヒーを淹れる <kbd>E</kbd>':'☕ 近くでコーヒーを渡す <kbd>E</kbd>';$('interact').disabled=brewing||(!n&&!atCafe&&!point);$('guide').textContent=walking.length?'道案内を止める':!state.cups&&state.delivered.length<8?'カフェへ道案内':'次のともだちへ';$('view').textContent=overview?'街に戻る':'星を眺める';$('place').textContent=state.h>3?'木の橋と、屋上のともだち':atCafe?'おけもんの森カフェ':state.z>14?'木もれ日の池':'森の、朝のひとまわり';}
$('interact').onclick=action;$('guide').onclick=nextGuide;$('home').onclick=()=>guide({x:0,z:3,h:0},'カフェ');$('jump').onclick=()=>{if(jump===0&&!brewing){jumpV=5.4;chime(330,.14);}};$('view').onclick=()=>{overview=!overview;updateUI();};$('welcome-close').onclick=closeWelcome;
function toggleBook(){const visible=$('book').hidden;$('book').hidden=!visible;$('book-toggle').setAttribute('aria-expanded',String(visible));} $('book-toggle').onclick=toggleBook;$('book-close').onclick=toggleBook;
$('help-toggle').onclick=()=>toast('歩き方','WASD・矢印で歩く / Eで渡す / 地面をクリック / ドラッグで見回す。道案内も使えるよ。');
$('sound').onclick=async()=>{audio||=new(window.AudioContext||window.webkitAudioContext)();await audio.resume();sound=!sound;$('sound').textContent=sound?'♫ 音あり':'♫ 音なし';$('sound').setAttribute('aria-pressed',String(sound));chime();};
$('reset').onclick=()=>$('reset-dialog').showModal();$('cancel-reset').onclick=()=>$('reset-dialog').close();function reset(){const round=state.round+1;state=fresh();state.round=round;walking=[];brewing=false;jump=0;jumpV=0;overview=false;zoom=10.4;orbit=.48;lastUi='';$('finish').close();$('reset-dialog').close();$('book').hidden=true;$('book-toggle').setAttribute('aria-expanded','false');$('welcome').hidden=false;toast('おけもんの森カフェ','おはよう。新しい朝の、はじまり。');save();updateUI();}$('confirm-reset').onclick=reset;$('new-morning').onclick=reset;$('keep-walking').onclick=()=>$('finish').close();
window.addEventListener('keydown',e=>{if(e.target.closest('dialog')||e.target.tagName==='INPUT')return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' '].includes(key)){e.preventDefault();keys.add(key);if(key===' '&&!e.repeat)$('jump').click();}if(!e.repeat){if(key==='e')action();if(key==='q')$('home').click();if(key==='j')$('journal-toggle').click();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);b.onlostpointercapture=()=>keys.delete(b.dataset.key);}
let pointer=null;const raycaster=new THREE.Raycaster();canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY,last:e.clientX,moved:false};canvas.focus();});canvas.addEventListener('pointermove',e=>{if(!pointer)return;if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>5)pointer.moved=true;if(pointer.moved){orbit-=(e.clientX-pointer.last)*.006;pointer.last=e.clientX;}});canvas.addEventListener('pointerup',e=>{if(pointer&&!pointer.moved&&ready&&!brewing&&!overview){raycaster.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);const hit=raycaster.intersectObject(planet)[0];if(hit){const p=hit.point.normalize(),x=Math.atan2(p.x,p.y)*R,z=Math.asin(p.z)*R;walking=[{x,z,h:0}];guideName='選んだ場所';closeWelcome();}}pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.015,9,36);overview=false;},{passive:false});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});document.addEventListener('visibilitychange',()=>{keys.clear();save();});window.addEventListener('pagehide',save);
let last=0;const look=new THREE.Vector3(),camPos=new THREE.Vector3();let initialized=false,stuckTime=0;
function renderFrame(ms){requestAnimationFrame(renderFrame);if(!ready)return;const dt=Math.min((ms-last)/1000,.06);last=ms;time+=dt;details?.update(dt);
if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('speech').classList.remove('show');}
if(brewing){brewTimer+=dt;if(brewTimer>.7){brewTimer=0;brewOne(state);chime(440+state.cups*75);if(state.cups===4){brewing=false;toast('おけもんの森カフェ','4杯、できあがり。みんなのところへ。');}save();updateUI();}}
let dx=0,dz=0;if(!brewing&&!$('finish').open&&!$('reset-dialog').open&&!$('journal').open){let sx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),sz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(sx||sz){walking=[];closeWelcome();dx=sx*Math.cos(orbit)+sz*Math.sin(orbit);dz=-sx*Math.sin(orbit)+sz*Math.cos(orbit);}else if(walking.length){const target=walking[0];dx=target.x-state.x;dz=target.z-state.z;if(Math.hypot(dx,dz)<.15){walking.shift();dx=dz=0;if(!walking.length){toast('道案内',`${guideName}に着いたよ。`);guideName='';}}}}
const moving=!!(dx||dz);if(moving){const len=Math.hypot(dx,dz),step=Math.min(len,3.4*dt);dx=dx/len*step;dz=dz/len*step;let moved=advance(state,dx,dz);if(!moved)moved=(Math.abs(dx)>.0001&&advance(state,dx,0))||(Math.abs(dz)>.0001&&advance(state,0,dz));if(!moved&&walking.length){stuckTime+=dt;if(stuckTime>1){walking=[];toast('小さなヒント','建物にぶつかったよ。道案内なら、小道を通れるよ。');stuckTime=0;}}else stuckTime=0;yaw=Math.atan2(dx,dz);}
if(jump>0||jumpV>0){jumpV-=12*dt;jump=Math.max(0,jump+jumpV*dt);if(jump===0)jumpV=0;}
place(courier,state.x,state.z,state.h+jump);body.rotation.y+=Math.atan2(Math.sin(yaw-body.rotation.y),Math.cos(yaw-body.rotation.y))*(1-Math.exp(-12*dt));body.position.y=moving?Math.abs(Math.sin(time*12))*.065:Math.sin(time*2)*.017;for(let i=0;i<footsteps.length;i++)footsteps[i].o.position.y=footsteps[i].y+(moving?Math.max(0,Math.sin(time*12+i*Math.PI))*.13:0);
for(let i=0;i<people.length;i++){const p=people[i];p.celebrate=Math.max(0,p.celebrate-dt);p.model.position.y=Math.sin(time*1.5+i)*.025+(p.celebrate>0?Math.abs(Math.sin(p.celebrate*7))*.15:0);p.model.rotation.z=Math.sin(time*1.3+i)*.022;p.model.rotation.y=Math.atan2(state.x-p.n.x,state.z-p.n.z);p.ring.scale.setScalar(1+Math.sin(time*2+i)*.04);}
const normal=at(state.x,state.z).normalize(),local=frame(state.x,state.z),aspectScale=innerWidth<600?1.3:1;const target=at(state.x,state.z,state.h+1.05);let desired;
if(overview){desired=at(state.x,state.z,R*2.6);desired.add(v3(Math.sin(orbit)*20,0,Math.cos(orbit)*24).applyMatrix4(local));look.lerp(v3(),1-Math.exp(-3*dt));}else{const offset=v3(Math.sin(orbit)*zoom,zoom*1.04,Math.cos(orbit)*zoom).multiplyScalar(aspectScale).applyMatrix4(local);desired=target.clone().add(offset);if(!initialized)look.copy(target);else look.lerp(target,1-Math.exp(-5*dt));}
if(!initialized){camPos.copy(desired);initialized=true;}camPos.lerp(desired,1-Math.exp(-4*dt));camera.position.copy(camPos);camera.up.lerp(normal,.08).normalize();camera.lookAt(look);updateUI();if(time-lastSave>3){save();lastSave=time;}renderer.render(scene,camera);}
load().catch(e=>{console.error(e);$('loading-message').textContent='街を読み込めませんでした。ページを再読み込みしてください。';});

function updateJournal(){const list=$('discoveries');list.replaceChildren();for(const p of PLACES){const article=document.createElement('section');article.className='entry'+(discovered.has(p.id)?' found':'');const h=document.createElement('h3');h.textContent=p.title;const text=document.createElement('p');text.textContent=discovered.has(p.id)?p.memory:p.hint;const button=document.createElement('button');button.textContent='ここへ歩いてみる';button.onclick=()=>{$('journal').close();guide(p,p.title);};article.append(h,text,button);list.append(article);}$('discovery-count').textContent=`${discovered.size} / ${PLACES.length} の発見`;}
$('journal-toggle').onclick=()=>{keys.clear();if($('journal').open)$('journal').close();else $('journal').showModal();};$('journal-close').onclick=()=>$('journal').close();
