import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {selectedProduct} from './app.js';
const stage=document.querySelector('#stage'),canvas=document.querySelector('#viewer'),status=document.querySelector('#viewer-status'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const state={loaded:false,id:'wanko',line:'figurine',rotation:0,paused:reduce.matches,view:'3d',error:null};window.keychain3D=state;
let renderer,scene,camera,pivot,model,request=0,dragging=false,lastX=0,lastY=0,targetY=-.20,targetX=.09,paused=reduce.matches,autoTime=0,lastFrame=performance.now();
let fitViewport=()=>{};
const cache=new Map(),loader=new GLTFLoader();
function fallback(msg){state.error=msg;state.loaded=false;stage.classList.add('photo');stage.classList.remove('loaded');status.textContent=msg;document.querySelectorAll('#rotate,#back,#pause').forEach(b=>b.disabled=true);}
function reset(){targetY=-.20;targetX=.09;document.querySelector('#back').textContent='うらを見る';}
async function loadProduct(p){const n=++request;state.id=p.id;state.line=p.line;canvas.dataset.product=p.key;state.loaded=false;canvas.dataset.loaded='false';reset();stage.classList.remove('loaded');status.textContent='立体を準備しています';try{let gltf=cache.get(p.key);if(!gltf){gltf=await loader.loadAsync(p.modelUrl);cache.set(p.key,gltf);}if(n!==request)return;if(model)pivot.remove(model);model=gltf.scene.clone(true);model.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3()),scale=3.3/Math.max(size.y,size.x);const wrapper=new THREE.Group();wrapper.add(model);model.position.sub(center);wrapper.scale.setScalar(scale);pivot.add(wrapper);model=wrapper;let meshes=0;model.traverse(o=>{if(o.isMesh){meshes++;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.envMapIntensity=.45;if(m.map){m.map.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);} });}});state.meshes=meshes;state.loaded=true;canvas.dataset.loaded='true';canvas.dataset.meshes=meshes;fitViewport();state.error=null;stage.classList.add('loaded');stage.classList.remove('photo');status.textContent='ドラッグで回せます';document.querySelectorAll('#rotate,#back,#pause').forEach(b=>b.disabled=false);}catch(e){if(n===request)fallback('3Dを読み込めませんでした。完成イメージをご覧ください。');}}
try{
if(new URLSearchParams(location.search).get('view')==='photo')throw new Error('photo');
renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(33,1,.01,80);camera.position.set(0,.12,8.3);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x849683,.8));const key=new THREE.DirectionalLight(0xfff5e9,1.8);key.position.set(-3,5,5);scene.add(key);const fill=new THREE.DirectionalLight(0xe7efff,.8);fill.position.set(4,1,2);scene.add(fill);const rim=new THREE.DirectionalLight(0xffffff,1.4);rim.position.set(1,4,-4);scene.add(rim);
const studio=new THREE.Scene();studio.background=new THREE.Color('#dce5ec');for(const [x,y,z,w,h] of [[-4,2,3,3,6],[4,4,2,3,4],[0,6,-2,6,3]]){const light=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide}));light.position.set(x,y,z);light.lookAt(0,0,0);studio.add(light);}const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(studio,.025).texture;pmrem.dispose();
pivot=new THREE.Group();pivot.position.y=.16;scene.add(pivot);
const shadow=new THREE.Mesh(new THREE.CircleGeometry(1.2,64),new THREE.MeshBasicMaterial({color:0x819183,transparent:true,opacity:.065,depthWrite:false}));shadow.scale.set(1,.2,1);shadow.position.set(0,-2.02,-.5);scene.add(shadow);
function resize(){const {width,height}=stage.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.position.z=Math.max(8.7,(state.line==='figurine'&&state.id!=='anbata'?4.0:6.7)/camera.aspect);camera.updateProjectionMatrix();}fitViewport=resize;new ResizeObserver(resize).observe(stage);resize();
canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!dragging)return;targetY+=(e.clientX-lastX)*.012;targetX=THREE.MathUtils.clamp(targetX+(e.clientY-lastY)*.007,-.65,.65);lastX=e.clientX;lastY=e.clientY;});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{dragging=false;});canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){targetY+=(e.key==='ArrowLeft'?-1:1)*.25;e.preventDefault();}if(e.key==='Home'){reset();e.preventDefault();}});
document.querySelector('#rotate').onclick=()=>{targetY+=Math.PI*2;document.querySelector('#back').textContent='うらを見る';};document.querySelector('#back').onclick=e=>{const back=e.currentTarget.textContent==='うらを見る';targetY=back?Math.PI:0;targetX=.05;e.currentTarget.textContent=back?'おもてを見る':'うらを見る';};document.querySelector('#pause').onclick=e=>{paused=!paused;state.paused=paused;e.currentTarget.textContent=paused?'動きを再開':'動きを止める';e.currentTarget.setAttribute('aria-pressed',paused);};if(paused){document.querySelector('#pause').textContent='動きを再開';document.querySelector('#pause').setAttribute('aria-pressed','true');}
reduce.addEventListener('change',e=>{paused=e.matches;state.paused=paused;document.querySelector('#pause').textContent=paused?'動きを再開':'動きを止める';document.querySelector('#pause').setAttribute('aria-pressed',paused);});
let visible=true;new IntersectionObserver(e=>visible=e[0].isIntersecting,{rootMargin:'100px'}).observe(stage);
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;if(!visible||document.hidden||state.view!=='3d')return;if(!paused)autoTime+=dt;const d=reduce.matches?1:1-Math.exp(-dt*5);pivot.rotation.y+=(targetY-pivot.rotation.y)*d;pivot.rotation.x+=(targetX-pivot.rotation.x)*d;pivot.rotation.z=paused?0:Math.sin(autoTime*.65)*.025;pivot.position.y=.12+(paused?0:Math.sin(autoTime*.95)*.035);state.rotation=Number(pivot.rotation.y.toFixed(3));canvas.dataset.rotation=state.rotation;state.tilt=Number(pivot.rotation.x.toFixed(3));renderer.render(scene,camera);}requestAnimationFrame(animate);loadProduct(selectedProduct);document.addEventListener('productchange',e=>loadProduct(e.detail));canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback('完成イメージに切り替えました。');});
}catch(e){fallback('完成イメージでご覧ください。');}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;stage.classList.toggle('original',state.view==='original');document.querySelector('#original').hidden=state.view!=='original';document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('#rotate,#back,#pause').forEach(x=>x.hidden=state.view==='original');}));
