import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {initialState,advance,moving,setValue,shifts,fitCamera,project,VIEWS,TAU} from '../model.mjs';
import {buildFixed,buildShell,buildAir,boundsPoints,transformPoint,shellAngles} from '../geometry.mjs';

test('initial state and reduced motion start are independently reproducible',()=>{const a=initialState(),b=initialState(true);assert.equal(a.playing,true);assert.equal(b.playing,false);assert.equal(a.cutaway,64);a.explode=100;assert.equal(initialState().explode,14);});
test('invalid input cannot poison geometry; ranges are clamped and angle uses radians',()=>{const s=initialState();assert.equal(setValue(s,'speed',NaN),false);assert.equal(s.speed,30);assert.equal(setValue(s,'unknown',42),false);setValue(s,'cutaway',1000);assert.equal(s.cutaway,100);setValue(s,'pitch',-99);assert.equal(s.pitch,-.18);setValue(s,'angle',180);assert.ok(Math.abs(s.angle-Math.PI)<1e-9);});
test('clock rejects initial/backwards/nonfinite deltas and caps restoration gaps',()=>{const s=initialState();const a=s.angle;for(const delta of[0,-3,NaN,Infinity])assert.equal(advance(s,delta),0);assert.equal(s.angle,a);assert.equal(advance(s,9),.05);assert.ok(Math.abs(s.angle-a-.036)<1e-10);});
test('paused and zero speed phases are exactly stable; resume and wrap are continuous',()=>{const s=initialState();s.playing=false;const a=s.angle;advance(s,.05);assert.equal(s.angle,a);s.playing=true;s.speed=0;advance(s,.05);assert.equal(s.angle,a);assert.equal(moving(s),false);s.speed=100;s.angle=TAU-.01;advance(s,.02);assert.ok(s.angle>0&&s.angle<.05);});
test('separation moves the two outer groups in opposite axial directions',()=>{assert.deepEqual(shifts(0),[-0,0,0]);assert.deepEqual(shifts(100),[-2.25,0,2.25]);const p=[-2,0,0],s=initialState();s.explode=100;assert.equal(transformPoint(p,{group:0,rotates:false},s)[0],-4.25);assert.equal(transformPoint(p,{group:1,rotates:false},s)[0],-2);});
test('cutaway removes an increasing real angular sector and keeps a finite casing',()=>{const widths=[0,50,100].map(c=>{const [a,b]=shellAngles(c);return b-a;});assert.ok(Math.abs(widths[0]-TAU)<1e-10);assert.ok(widths[0]>widths[1]&&widths[1]>widths[2]);assert.ok(widths[2]>Math.PI*.9);for(const c of[0,50,100])for(const p of buildShell(c)){assert.ok(p.mesh.data.length>0);assert.equal(p.mesh.data.length%18,0);assert.ok(p.mesh.data.every(Number.isFinite));}for(const part of buildShell(0).filter(p=>p.material==='steel'))assert.equal(part.mesh.data.length,28*4*6*6*6,'all 14 bolts on both closed rims, including the zero-angle seam');});
test('solid geometry has finite unit normals, curved blades and distinct materials',()=>{const parts=buildFixed();const materials=new Set(parts.map(p=>p.material));for(const name of['steel','brass','dark','base','rubber'])assert.ok(materials.has(name));for(const part of parts){const d=part.mesh.data;assert.equal(d.length%18,0);assert.ok(d.every(Number.isFinite));for(let i=0;i<d.length;i+=6){const n=Math.hypot(d[i+3],d[i+4],d[i+5]);assert.ok(n>.999&&n<1.001,`${part.name}: non-unit normal`);}}const fan=parts.find(p=>p.name==='入口の羽根').mesh.data,x=[];for(let i=0;i<fan.length;i+=6)x.push(fan[i]);assert.ok(Math.max(...x)-Math.min(...x)>.60);assert.notDeepEqual(fan.slice(3,6),fan.slice(9,12),'surface normals vary continuously within each face');});
test('actual geometry fits across cut/separation extremes, preset/orbit angles and narrow screens',()=>{const fixed=buildFixed();const angles=[...Object.values(VIEWS),{yaw:-Math.PI,pitch:-.18},{yaw:Math.PI/2,pitch:1.4},{yaw:1.2,pitch:.5},{yaw:2.8,pitch:.8}];let checked=0;for(const cutaway of[0,50,100]){const all=[...fixed,...buildShell(cutaway)];for(const explode of[0,50,100])for(const v of angles)for(const aspect of[.62,1.60]){const s={...initialState(),...v,cutaway,explode,angle:2.18};const cam=fitCamera(boundsPoints(s),s,aspect);for(const part of all){const d=part.mesh.data;for(let i=0;i<d.length;i+=6){const q=project(transformPoint(d.slice(i,i+3),part,s),cam);assert.ok(q.every(Number.isFinite));assert.ok(Math.abs(q[0])<=.94&&Math.abs(q[1])<=.94,`${cutaway}/${explode}/${aspect}: outside ${q}`);checked++;}}for(const part of[buildAir(s)])for(let i=0;i<part.mesh.data.length;i+=6){const q=project(part.mesh.data.slice(i,i+3),cam);assert.ok(Math.abs(q[0])<.98&&Math.abs(q[1])<.98);}}}assert.ok(checked>1000000);});
test('making displays the exact reusable prompt and no network dependencies are introduced',()=>{const dir=new URL('../',import.meta.url);const prompt=fs.readFileSync(new URL('prompts/reusable-prompt.txt',dir),'utf8').trim();const html=fs.readFileSync(new URL('making.html',dir),'utf8');const shown=html.match(/<code id="reusable-prompt">([\s\S]*?)<\/code>/)[1].replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&');assert.equal(shown,prompt);for(const name of['index.html','making.html','app.mjs','renderer.mjs','geometry.mjs','style.css']){const text=fs.readFileSync(new URL(name,dir),'utf8');assert.equal(/(?:src|href)=["']https?:\/\//.test(text),false,name);assert.equal(/fetch\(|XMLHttpRequest|WebSocket/.test(text),false,name);}});
