import {fitCamera,shifts} from './model.mjs';
import {MATERIALS,CENTER,buildFixed,buildShell,buildAir,boundsPoints} from './geometry.mjs';
const vertex=`attribute vec3 position;attribute vec3 normal;uniform mat4 camera;uniform float rotation;uniform vec3 translation;varying vec3 p;varying vec3 n;
void main(){float c=cos(rotation),s=sin(rotation);p=vec3(position.x,position.y*c-position.z*s,position.y*s+position.z*c)+translation;n=vec3(normal.x,normal.y*c-normal.z*s,normal.y*s+normal.z*c);gl_Position=camera*vec4(p,1.);}`;
const fragment=`precision highp float;varying vec3 p;varying vec3 n;uniform vec3 color;uniform vec3 eye;uniform float metal;uniform float rough;uniform float emission;
void main(){vec3 N=normalize(n);if(!gl_FrontFacing)N=-N;vec3 V=normalize(eye);vec3 L=normalize(vec3(-.5,.9,.7));vec3 R=reflect(-V,N);float lam=max(0.,dot(N,L));float fill=max(0.,dot(N,normalize(vec3(.7,.5,-.4))));float ndv=max(.0,dot(N,V));float fres=pow(1.-ndv,4.);float spec=pow(max(0.,dot(N,normalize(L+V))),mix(100.,14.,rough));
float window=pow(max(0.,dot(R,normalize(vec3(-.4,.75,.8)))),14.);float strip=pow(max(0.,1.-abs(R.y-.45)*2.),10.);vec3 env=mix(vec3(.22,.29,.31),vec3(.90,.87,.76),smoothstep(-.45,.80,R.y));
vec3 c=color*(.43+.48*lam+.18*fill);c=mix(c,c*.77+env*color*.48,metal);c+=vec3(1.,.94,.79)*spec*(.22+metal*.40);c+=(window*.16+strip*.08)*mix(vec3(1.),color,.38)*metal;c+=fres*.07*metal;
float grain=sin(p.x*780.+sin(p.z*400.)*.4)*sin(p.y*390.+p.z*510.);c*=1.+grain*.017*metal;c+=color*emission;gl_FragColor=vec4(c,1.);}`;
const bgVertex=`attribute vec2 position;varying vec2 uv;void main(){uv=position;gl_Position=vec4(position,0.,1.);}`;
const bgFragment=`precision mediump float;varying vec2 uv;void main(){float vign=length(uv*vec2(.62,.42));vec3 c=mix(vec3(.944,.935,.907),vec3(.866,.876,.850),vign*.56);float glow=exp(-length((uv-vec2(-.5,.5))*vec2(1.2,1.5))*2.);c+=glow*.025;gl_FragColor=vec4(c,1.);}`;
const floorFragment=`precision highp float;varying vec3 p;varying vec3 n;void main(){float d=length(p.xz/vec2(4.42,1.97));float shadow=exp(-d*d*2.8)*.27;float contact=exp(-pow(length(p.xz/vec2(3.8,1.43)),6.)*2.)*.12;vec3 c=vec3(.924,.924,.890)*(1.-shadow-contact);float fade=clamp(length(p.xz)/12.,0.,1.);gl_FragColor=vec4(c,1.-fade);}`;
function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
function program(gl,vs,fs){const p=gl.createProgram(),v=shader(gl,gl.VERTEX_SHADER,vs),f=shader(gl,gl.FRAGMENT_SHADER,fs);gl.attachShader(p,v);gl.attachShader(p,f);gl.linkProgram(p);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
export class Renderer{
 constructor(canvas){this.canvas=canvas;const gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true,premultipliedAlpha:false});if(!gl)throw new Error('WebGL unavailable');this.gl=gl;this.solid=program(gl,vertex,fragment);this.floor=program(gl,vertex,floorFragment);this.bg=program(gl,bgVertex,bgFragment);this.fixed=buildFixed();this.shell=[];this.buffers=new Map();this.cut=-1;this.frames=0;this.airBuffer=gl.createBuffer();this.bgBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.bgBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,1,1,-1,-1,1,1,-1,1]),gl.STATIC_DRAW);
 const data=[];for(const p of[[-14,-.27,-14],[14,-.27,-14],[14,-.27,14],[-14,-.27,-14],[14,-.27,14],[-14,-.27,14]])data.push(...p,0,1,0);this.floorPart={mesh:{data},material:'base',group:-1};
 }
 upload(part,dynamic=false){const gl=this.gl;let buffer=this.buffers.get(part);if(!buffer){buffer=gl.createBuffer();this.buffers.set(part,buffer);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(part.mesh.data),dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);}else gl.bindBuffer(gl.ARRAY_BUFFER,buffer);return buffer;}
 attributes(p){const gl=this.gl;for(const [name,offset] of[['position',0],['normal',12]]){const a=gl.getAttribLocation(p,name);if(a>=0){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,24,offset);}}}
 drawPart(part,p,state,camera,dynamic=false){const gl=this.gl;gl.useProgram(p);if(dynamic){gl.bindBuffer(gl.ARRAY_BUFFER,this.airBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(part.mesh.data),gl.DYNAMIC_DRAW);}else this.upload(part);this.attributes(p);gl.uniformMatrix4fv(gl.getUniformLocation(p,'camera'),false,camera.matrix);gl.uniform1f(gl.getUniformLocation(p,'rotation'),part.rotates?state.angle:0);gl.uniform3f(gl.getUniformLocation(p,'translation'),part.group>=0?shifts(state.explode)[part.group]:0,part.group>=0?CENTER:0,0);const mat=MATERIALS[part.material];gl.uniform3fv(gl.getUniformLocation(p,'color'),mat.color);gl.uniform3fv(gl.getUniformLocation(p,'eye'),camera.eye);for(const k of['metal','rough','emission'])gl.uniform1f(gl.getUniformLocation(p,k),mat[k]||0);gl.drawArrays(gl.TRIANGLES,0,part.mesh.data.length/6);}
 draw(state){
  const gl=this.gl,canvas=this.canvas,rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);const w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}
  if(this.cut!==state.cutaway){for(const part of this.shell){const b=this.buffers.get(part);if(b)gl.deleteBuffer(b);this.buffers.delete(part);}this.shell=buildShell(state.cutaway);this.cut=state.cutaway;}
  const camera=fitCamera(boundsPoints(state),state,w/h);this.camera=camera;
  gl.viewport(0,0,w,h);gl.clearColor(.93,.93,.90,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.disable(gl.CULL_FACE);gl.useProgram(this.bg);gl.bindBuffer(gl.ARRAY_BUFFER,this.bgBuffer);const a=gl.getAttribLocation(this.bg,'position');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,8,0);gl.drawArrays(gl.TRIANGLES,0,6);
  gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.drawPart(this.floorPart,this.floor,state,camera);gl.disable(gl.BLEND);
  for(const part of[...this.fixed,...this.shell])this.drawPart(part,this.solid,state,camera);
  if(state.airflow)this.drawPart(buildAir(state),this.solid,state,camera,true);gl.flush();this.frames++;
  this.stats={frames:this.frames,width:w,height:h,triangles:[...this.fixed,...this.shell].reduce((n,p)=>n+p.mesh.data.length/18,0),depthBits:gl.getParameter(gl.DEPTH_BITS),antialias:gl.getContextAttributes().antialias};return this.stats;
 }
}
