import * as THREE from './vendor/three.module.js';
import {referenceTown,commuteTown} from './reference-study.mjs';
import {komorebiTown} from './komorebi.mjs';
import {EffectComposer} from './vendor/addons/postprocessing/EffectComposer.js';
import {RenderPass} from './vendor/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from './vendor/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from './vendor/addons/postprocessing/OutputPass.js';
import {SIZE,CELL,TYPES,newTown,placeBlock,dragPlots,validatePlots,boundaryEdges,roadNetwork,shortestPath,key,stage,inspectionStats,residentAdditions,jobCapacity,jobAssignments,parseSave,seeded} from './simulation.mjs';
import {box,material,building,streetLamp,terrain,person,car,nightMaterials,clearNightLights} from './models.mjs';
const study=new URLSearchParams(location.search).get('town')==='reference',commute=study&&new URLSearchParams(location.search).get('scene')==='commute';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={home:'M2 11 12 2 22 11v11h-7v-8H9v8H2zm4 1v4h3v-4zm9 0v4h3v-4z',explore:'M4 2v19l5-5 4 7 3-2-4-7h8z',shop:'M4 3h16l3 8h-2v11H3V11H1zm2 9v7h5v-7zm8 0v7h4v-7zM5 5l-1 4h3l1-4zm6 0-1 4h4l-1-4zm5 0 1 4h3l-1-4z',work:'M3 5h10V2h7v20h-6v-5h-3v5H3zm3 3v3h3V8zm0 6v3h3v-3zm7-6v3h3V8zm0 6v2h3v-2z',park:'M10 1h4v3h4v4h4v7h-8v4h7v3H3v-3h7v-4H2V8h4V4h4zm-3 8v3h10V9z',sun:'M9 0h6v4H9zm0 20h6v4H9zM0 9h4v6H0zm20 0h4v6h-4zM6 6h12v12H6zM2 3l2-2 3 3-3 3zm16 17 3-3 2 2-3 3zM2 20l3-3 2 2-3 3zm15-16 3-3 2 2-3 3z'};
$$('[data-icon]').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="${icons[el.dataset.icon]}"></path></svg>`);
const world=$('#world'),scene=new THREE.Scene();scene.background=new THREE.Color(0xb8d6dd);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('#error').hidden=false;throw e;}
renderer.setPixelRatio(study?.5:Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;world.append(renderer.domElement);
renderer.domElement.setAttribute('aria-label','立体の街。ドラッグで区画配置またはカメラ移動。');
const camera=new THREE.OrthographicCamera(-30,30,20,-20,.1,160);const DEFAULT_ZOOM=innerWidth<760?1:1.44;let zoom=DEFAULT_ZOOM,angle=Math.PI/4,target=new THREE.Vector3(0,0,0);
function updateCamera(){const aspect=innerWidth/innerHeight;const span=(innerWidth<760?24:24)/zoom;camera.left=-span*aspect;camera.right=span*aspect;camera.top=span;camera.bottom=-span;camera.position.set(target.x+Math.sin(angle)*46,study?26.56:43,target.z+Math.cos(angle)*46);camera.lookAt(target.x,0,target.z);camera.updateProjectionMatrix();}
updateCamera();const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.45,.65,.9);composer.addPass(bloom);composer.addPass(new OutputPass());const hemi=new THREE.HemisphereLight(0xe8f2e7,0x798c55,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffebc7,2.8);sun.position.set(-18,35,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:95});sun.shadow.bias=-.0006;sun.shadow.normalBias=.025;sun.shadow.radius=4;scene.add(sun);scene.add(sun.target);
if(study)renderer.domElement.style.imageRendering='pixelated';
const land=terrain(scene,study);
// Static scenery shares geometry: instance equal meshes to keep the large playfield light.
function instanceScenery(group){const buckets=new Map();group.updateMatrixWorld(true);group.traverse(o=>{if(o.isMesh){const k=o.geometry.uuid+'|'+o.material.uuid;if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(o);}});for(const list of buckets.values()){if(list.length<3)continue;const inst=new THREE.InstancedMesh(list[0].geometry,list[0].material,list.length);list.forEach((m,i)=>inst.setMatrixAt(i,m.matrixWorld));inst.castShadow=true;inst.receiveShadow=true;scene.add(inst);for(const m of list)m.parent.remove(m);}}
instanceScenery(land);
const grid=new THREE.GridHelper(SIZE*CELL,SIZE*4,0x7d9255,0x879b60);grid.position.y=.03;grid.material.transparent=true;grid.material.opacity=.2;scene.add(grid);
const plotGrid=new THREE.GridHelper(SIZE*CELL,SIZE,0x889951,0x819854);plotGrid.position.y=.035;plotGrid.material.transparent=true;plotGrid.material.opacity=.18;scene.add(plotGrid);
const structureGroup=new THREE.Group(),roadGroup=new THREE.Group(),peopleGroup=new THREE.Group(),previewGroup=new THREE.Group();scene.add(structureGroup,roadGroup,peopleGroup,previewGroup);
let scenic=false;
let town=newTown(),network=roadNetwork(town),mode='explore',speed=1,previousSpeed=1,drag=null,hoverPlot=null,inspectId=null,inspectPlot=0,agents=[],cars=[],blockViews=new Map(),eventList=[],lastSimMinute=-1;
const offset=SIZE*CELL/2;const nodeWorld=([x,z])=>new THREE.Vector3(x*CELL-offset,.1,z*CELL-offset);const plotWorld=([x,z])=>new THREE.Vector3((x+.5)*CELL-offset,.1,(z+.5)*CELL-offset);
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),point=new THREE.Vector3();
function groundPoint(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster.ray.intersectPlane(ground,point)?.clone();}
function plotAt(e){const p=groundPoint(e);if(!p)return null;const x=Math.floor((p.x+offset)/CELL),z=Math.floor((p.z+offset)/CELL);return x>=0&&z>=0&&x<SIZE&&z<SIZE?[x,z]:null;}
function timeLabel(time=town.time){const m=Math.floor(time%1440);return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;}
function event(text){eventList.unshift({text,time:timeLabel()});eventList=eventList.slice(0,3);$('#events').innerHTML=eventList.map(e=>`<li>${e.text}<time>${e.time}</time></li>`).join('');}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3300);}
function clearGroup(g){clearNightLights(g);for(const child of [...g.children]){g.remove(child);child.traverse(o=>{if(o.geometry&&o.geometry.type!=='BoxGeometry')o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose();}});}}
function rebuildRoads(){clearGroup(roadGroup);network=roadNetwork(town);
 for(const [a,b]of network.edges){const p=nodeWorld(a),q=nodeWorld(b),mx=(p.x+q.x)/2,mz=(p.z+q.z)/2,horizontal=a[1]===b[1];box(roadGroup,mx,.044,mz,horizontal?CELL+.8:1,.075,horizontal?1:CELL+.8,study?0x85816f:0xc0bba0);box(roadGroup,mx,.089,mz,horizontal?CELL+.74:.72,.028,horizontal?.72:CELL+.74,study?0x40475b:0x626e64);
  for(let i=0;i<3;i++){const off=-1.35+i*1.35;box(roadGroup,mx+(horizontal?off:0),.108,mz+(horizontal?0:off),horizontal?.49:.035,.008,horizontal?.035:.49,0xd0cb9e);}}
 const placed=new Set();for(const b of town.blocks){const edges=boundaryEdges(b.plots);for(let i=0;i<edges.length;i++){
  if(!study&&i%2!==0)continue;if(study&&[1,4].includes(i)&&b.plots.length===3&&b.plots.every(p=>p[1]===b.plots[0][1]))continue;
  const [a,c]=edges[i];const x=a[0]*CELL-offset,z=a[1]*CELL-offset,k=key(...a);if(placed.has(k))continue;placed.add(k);
  // Place lamps on the outside pavement, not among the houses.
  const dx=c[0]-a[0],dz=c[1]-a[1];
  streetLamp(roadGroup,x+dx*.55+dz*.38,z+dz*.55-dx*.38,study);
 }}

 cars.forEach(c=>peopleGroup.remove(c.mesh));cars=[];const nodes=[...network.graph.keys()];if(nodes.length>0){const count=study?0:Math.min(12,Math.floor(town.blocks.reduce((n,b)=>n+b.plots.length,0)/2));for(let i=0;i<count;i++){const k=nodes[(i*7)%nodes.length],mesh=car(i*71);peopleGroup.add(mesh);const pos=nodeWorld(k.split(',').map(Number));mesh.position.copy(pos);cars.push({mesh,node:k,previous:null,target:null,progress:0});}}
}
function redrawBlock(block){const old=blockViews.get(block.id);if(old){for(const m of old.meshes){clearNightLights(m);structureGroup.remove(m);m.traverse(o=>{if(o.geometry&&o.geometry.type!=='BoxGeometry')o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose();}});}}
 const phase=stage(block,town.time);const meshes=block.plots.map((p,i)=>{const m=building(block,p,i,phase);structureGroup.add(m);return m;});blockViews.set(block.id,{phase,meshes});syncMarkers();}
const markerLayer=$('#building-markers');let markers=[];
function syncMarkers(){
 markerLayer.replaceChildren();markers=[];
 for(const block of town.blocks){if(block.style!=='reference'||stage(block,town.time)<3)continue;
  block.plots.forEach((plot,index)=>{const button=document.createElement('button');button.className='building-marker';button.type='button';button.setAttribute('aria-label',`${TYPES[block.type].name} ${block.id}−${index+1} の人を見る`);button.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[block.type]}"/></svg>`;button.onclick=()=>showInspect(block.id,index);markerLayer.append(button);const position=plotWorld(plot);position.y=stage(block,town.time)>=4?3.2:2.65;markers.push({button,position});});
 }
}
function positionMarkers(){for(const {button,position} of markers){const p=position.clone().project(camera);button.style.transform=`translate(${(p.x+1)*innerWidth/2}px,${(1-p.y)*innerHeight/2}px) translate(-50%,-100%)`;button.hidden=p.z>1||p.z< -1;}}
function addPlots(type,plots){const b=placeBlock(town,type,plots);if(!b){toast('空いている区画を、つなげて選んでね');return false;}redrawBlock(b);rebuildRoads();$('#welcome').hidden=true;event(`${plots.length}区画の${TYPES[type].name}を着工。道がつながりました。`);toast(`${plots.length}区画で、ひとつの街区に`);updateHUD();return true;}
function blockForPlot(plot){return town.blocks.find(b=>b.plots.some(p=>p[0]===plot[0]&&p[1]===plot[1]));}
const previewValid=new THREE.MeshBasicMaterial({color:0xaabb77,transparent:true,opacity:.42,depthWrite:false});const previewInvalid=new THREE.MeshBasicMaterial({color:0xcc6650,transparent:true,opacity:.42,depthWrite:false});
function preview(plots){clearGroup(previewGroup);if(mode==='explore'||!plots?.length)return;const valid=validatePlots(town,plots);const mat=valid?previewValid:previewInvalid;previewValid.color.setHex(TYPES[mode].color);for(const p of plots){const v=plotWorld(p);const m=box(previewGroup,v.x,.12,v.z,3.85,.07,3.85,mat);m.castShadow=false;}
 $('#placement-hint').textContent=valid?`${TYPES[mode].name} · ${plots.length}区画をひとつの街区に`:'ここには置けません · 空いている区画を選ぶ';}
function selectMode(m){mode=m;grid.visible=plotGrid.visible=(!scenic||m!=='explore');$$('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.zone===m));clearGroup(previewGroup);grid.material.opacity=m==='explore'?.09:.22;plotGrid.material.opacity=m==='explore'?.08:.28;$('#placement-hint').textContent=m==='explore'?'探索 · ドラッグで移動 / ホイールで拡大':`${TYPES[m].name} · クリックで1区画 / ドラッグで最大3区画`;world.style.cursor=m==='explore'?'grab':'crosshair';if(m!=='explore')$('#welcome').hidden=true;}
function setSpeed(n){speed=n;if(n>0)previousSpeed=n;$$('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.speed)===n));}
function entry(block,plotIndex=0){const p=plotWorld(block.plots[plotIndex]||block.plots[0]),edges=boundaryEdges(block.plots);let best=edges[0],distance=Infinity;for(const e of edges){const mid=nodeWorld(e[0]).add(nodeWorld(e[1])).multiplyScalar(.5);const dist=mid.distanceTo(p);if(dist<distance){distance=dist;best=e;}}return {inside:p,a:best[0],b:best[1],mid:nodeWorld(best[0]).add(nodeWorld(best[1])).multiplyScalar(.5)};}
const names=['はる','そら','りん','あお','ゆい','なぎ','けい','まき','ひな','こう','すず','れん','もも','みお','そう','ふう'];
function makeResidents(block){
 const additions=residentAdditions(block,town.time,agents);
 for(const resident of additions){const {id,homePlot}=resident,mesh=person(id*129);peopleGroup.add(mesh);mesh.visible=false;mesh.position.copy(entry(block,homePlot).inside);
 agents.push({...resident,name:names[id%names.length],home:block.id,currentPlot:homePlot,current:block.id,destination:block.id,job:null,mesh,route:null,step:0,phase:seeded(id)()*7,status:'家でくつろぎ中'});}
 if(additions.length)event(`${additions.length}人が新しい家へ。街に暮らしが生まれました。`);
}
function go(agent,destination){const from=town.blocks.find(b=>b.id===agent.current),to=town.blocks.find(b=>b.id===destination);if(!from||!to||from.id===to.id)return;
 agent.destinationPlot=to.id===agent.home?agent.homePlot:to.id===agent.job?agent.jobPlot:agent.id%to.plots.length;const a=entry(from,agent.currentPlot),b=entry(to,agent.destinationPlot);let best=null;for(const start of [a.a,a.b])for(const end of [b.a,b.b]){const path=shortestPath(network.graph,key(...start),key(...end));if(path&&(!best||path.length<best.length))best=path;}
 if(!best){agent.status='道がつながるのを待っています';return;}
 const route=[a.inside,a.mid,...best.map(nodeWorld),b.mid,b.inside];for(let i=2;i<route.length-2;i++){const next=route[Math.min(i+1,route.length-1)],prev=route[i-1];const direction=next.clone().sub(prev).normalize();route[i].x+=direction.z*.43;route[i].z-=direction.x*.43;}agent.route=route;agent.step=1;agent.mesh.position.copy(route[0]);agent.mesh.visible=true;agent.destination=destination;agent.status=to.type==='work'?'仕事場へ移動中':to.type==='shop'?'買い物へ移動中':to.type==='park'?'公園へ散歩中':'家へ帰るところ';}
function schedules(){const ready=town.blocks.filter(b=>stage(b,town.time)>=3),work=ready.filter(b=>b.type==='work'),shop=ready.filter(b=>b.type==='shop'),parks=ready.filter(b=>b.type==='park'),hour=(town.time%1440)/60;
 const assignments=jobAssignments(ready,town.time,agents);for(let i=0;i<agents.length;i++){const a=agents[i];Object.assign(a,assignments[i]);if(a.route)continue;let dest=a.home;
 if(hour>=8+(a.id%3)*.3&&hour<16.7&&a.job)dest=a.job;
 else if(hour>=17&&hour<19.5&&shop.length)dest=shop[a.id%shop.length].id;
 else if(hour>=12&&hour<16&&!a.job&&parks.length)dest=parks[a.id%parks.length].id;
 else if(hour>=19.5&&hour<20.5&&parks.length&&a.id%2===0)dest=parks[a.id%parks.length].id;
 if(dest!==a.current)go(a,dest);else{const b=town.blocks.find(b=>b.id===dest);a.status=b?.type==='work'?'仕事中':b?.type==='shop'?'お買い物中':b?.type==='park'?'公園でひと休み':'家でくつろぎ中';}}
}
function moveAgents(dt){for(const a of agents){if(!a.route)continue;let remain=dt*(.9+(a.id%7)*.07);while(remain>0&&a.route){const target=a.route[a.step],v=target.clone().sub(a.mesh.position);v.y=0;const d=v.length();if(d<remain){a.mesh.position.copy(target);remain-=d;a.step++;if(a.step>=a.route.length){a.current=a.destination;a.currentPlot=a.destinationPlot;a.route=null;a.mesh.visible=false;if(a.current===a.job){a.status='仕事中';event(`${a.name}が仕事場に到着しました。`);}break;}}else{v.normalize();a.mesh.position.addScaledVector(v,remain);a.mesh.rotation.y=Math.atan2(v.x,v.z);remain=0;}}
 a.phase+=dt*8;const limbs=a.mesh.userData.limbs;limbs.forEach((m,i)=>m.rotation.x=Math.sin(a.phase+(i%2)*Math.PI)*.55);}
 for(const c of cars){if(!c.target){const neighbors=network.graph.get(c.node)||[];const options=neighbors.filter(n=>n!==c.previous);const dest=(options.length?options:neighbors)[Math.floor(Math.random()*(options.length||neighbors.length))];if(!dest)continue;c.target=dest;c.progress=0;c.start=nodeWorld(c.node.split(',').map(Number));c.end=nodeWorld(dest.split(',').map(Number));}
  c.progress+=dt*2/CELL;const v=c.end.clone().sub(c.start).normalize();c.mesh.position.lerpVectors(c.start,c.end,Math.min(1,c.progress));c.mesh.position.x+=v.z*.16;c.mesh.position.z-=v.x*.16;c.mesh.rotation.y=Math.atan2(v.x,v.z);if(c.progress>=1){c.previous=c.node;c.node=c.target;c.target=null;}}
}
function updateHUD(){const hour=(town.time%1440)/60;$('#time').textContent=timeLabel();$('#day').textContent=`DAY ${Math.floor(town.time/1440)+1} · ${hour<5||hour>=20?'夜':hour<7?'夜明け':hour<17?'昼':hour<20?'夕暮れ':'夜'}`;$('#dayprogress').style.left=`${town.time%1440/1440*100}%`;$('#population').textContent=agents.length;const jobs=town.blocks.filter(b=>b.type==='work'&&stage(b,town.time)>=3).reduce((n,b)=>n+b.plots.length*jobCapacity(b,town.time),0);$('#jobs').textContent=`${agents.filter(a=>a.job).length}/${jobs}`;$('#shops').textContent=town.blocks.filter(b=>b.type==='shop'&&stage(b,town.time)>=3).reduce((n,b)=>n+b.plots.length,0);$('#parks').textContent=town.blocks.filter(b=>b.type==='park'&&stage(b,town.time)>=3).reduce((n,b)=>n+b.plots.length,0);$('#moving').textContent=agents.filter(a=>a.route).length;}
function showInspect(id,plot=inspectPlot){
 inspectId=id;inspectPlot=plot;const b=town.blocks.find(b=>b.id===id);if(!b)return;
 const info=inspectionStats(b,plot,agents,town.time),phase=stage(b,town.time);
 $('#inspect').hidden=false;
 $('#inspect-type').textContent=`${TYPES[b.type].name} · ${b.style==='reference'&&info.ready?`TIER ${phase>=4?3:2} · `:''}${b.plots.length}区画の街区`;
 $('#inspect-name').textContent=`${{home:'小さな家',shop:'まちかど商店',work:'小さな仕事場',park:'みどりの公園'}[b.type]} ${b.id}−${plot+1}`;
 const workers=agents.filter(a=>a.job===id&&a.jobPlot===plot),visitors=b.type==='work'?info.visitors.filter(a=>a.job!==id||a.jobPlot!==plot):info.visitors;const list=b.type==='home'?info.residents:b.type==='work'?workers:info.present;
 let body=`<div class="building-status ${info.ready?'open':''}">${info.ready?'利用できます':'建築中'}</div><div class="inspect-stats"><div><b>${b.type==='home'?`${info.residents.length}/${info.capacity}`:b.type==='work'?`${workers.length}/${jobCapacity(b,town.time)}`:info.present.length}</b><span>${b.type==='home'?'住民':b.type==='work'?'働く人':'いまここに'}</span></div><div><b>${visitors.length}</b><span>訪問者</span></div></div>`;
 if(!info.ready){body+=`<section class="growth"><div><span>建築の進み具合</span><b>${info.construction}%</b></div><progress aria-label="建築の進み具合" max="100" value="${info.construction}"></progress><small>${['基礎をつくっています','柱と梁を組み立て中','壁と屋根を仕上げています'][phase]}</small></section>`;}
 else if(b.style==='reference'){body+=`<section class="growth"><div><span>街区の成長</span><b>${info.growth===100?'成長しました':info.growth+'%'}</b></div>${info.growth<100?`<progress aria-label="街区の成長" max="100" value="${info.growth}"></progress>`:''}<small>${info.growth===100?(b.type==='home'?'TIER 3 · 住民が6人になりました':'TIER 3 · 10人が働けます'):'TIER 3へ育っています'} · 進み方は観察からの近似</small></section>`;}
 else{body+=`<section class="growth"><div><span>庭・建物の成長</span><b>${info.growth}%</b></div><progress aria-label="庭・建物の成長" max="100" value="${info.growth}"></progress><small>${info.growth===100?'成長しました':'時間とともに育ちます'}</small></section>`;}
 body+=`<section class="activity"><h3>人と暮らし <span>PEOPLE & ACTIVITY</span></h3><div class="resident-label">${b.type==='home'?'この家の住民':b.type==='work'?'ここで働く人':'ここにいる人'}<b>${list.length}</b></div>`;
 body+=list.length?`<ul>${list.map(a=>`<li><span class="person-initial" aria-hidden="true">${a.name[0]}</span><div><b>${a.name}</b><small>${a.home===id&&a.homePlot===plot?'この家の住民':a.job===id?'ここで働いています':'訪問中'}</small></div><span class="person-status">${a.status}</span></li>`).join('')}</ul>`:`<p>${info.ready?'いまは誰もいません。':'完成すると暮らしがはじまります。'}</p>`;
 if(b.type==='work')body+=`<p>働ける人数 ${jobCapacity(b,town.time)}人 · いま仕事中 ${workers.filter(a=>a.current===id&&a.currentPlot===plot&&!a.route).length}人</p>`;
 $('#inspect-body').innerHTML=body+'</section>';
}
const nightColor=new THREE.Color(0x273c58),dayColor=new THREE.Color(0xb8d6dd),duskColor=new THREE.Color(0xbe9584);
function lighting(){const hour=town.time%1440/60;const daylight=THREE.MathUtils.smoothstep(hour,5,8)*(1-THREE.MathUtils.smoothstep(hour,17,21));const night=1-daylight;if(study&&mode==='explore'){grid.material.opacity=.025+daylight*.09;plotGrid.material.opacity=.025+daylight*.045;}scene.background.copy(nightColor).lerp(dayColor,daylight);if(hour>17&&hour<20)scene.background.lerp(duskColor,Math.sin((hour-17)/3*Math.PI)*.65);hemi.intensity=(study?.95:.9)+daylight*1.0;hemi.color.setHex(night>.5?(study?0x729caf:0x93b2e3):0xe8f2e7);hemi.groundColor.setHex(night>.5?(study?0x294d4a:0x344957):0x798c55);sun.intensity=(study?.18:.3)+daylight*2.07;sun.color.setHex(hour>16&&hour<20?0xffb47a:night>.6?0x8dace0:0xffebc7);nightMaterials(night,study);bloom.strength=study?.15:.07+night*.5;document.body.classList.toggle('night',night>.5);}
let fpsFrames=0,fpsStart=performance.now();
function renderTick(now){requestAnimationFrame(renderTick);fpsFrames++;if(now-fpsStart>2000){world.dataset.fps=String(Math.round(fpsFrames*1000/(now-fpsStart)));fpsStart=now;fpsFrames=0;}const realDt=Math.max(0,Math.min((now-lastTime)/1000,.05));lastTime=now;const dt=realDt*speed;town.time+=dt*(scenic&&!study?.35:6);
 for(const b of town.blocks){const phase=stage(b,town.time);if(blockViews.get(b.id)?.phase!==phase){redrawBlock(b);if(phase===3){if(b.type==='home')makeResidents(b);else event(`${TYPES[b.type].name}がオープンしました。`);}if(phase===4){if(b.style==='reference')makeResidents(b);event(`${TYPES[b.type].name}が育ち、街の景色が変わりました。`);}}}
 if(Math.floor(town.time)!==lastSimMinute){lastSimMinute=Math.floor(town.time);schedules();updateHUD();if(inspectId&&!$('#inspect').hidden)showInspect(inspectId);}moveAgents(dt);for(const view of blockViews.values())for(const mesh of view.meshes)if(mesh.userData.fountain)mesh.userData.fountain.scale.y=1+Math.sin(town.time*.15)*.15;lighting();positionMarkers();composer.render();
}
let lastTime=performance.now();
function reset(t=newTown()){document.title='MiniTown｜おけもんのTTP実験 001';scenic=false;document.body.classList.remove('scenic','reference-study');setViewChrome(false);$('#town-view').hidden=true;town=t;clearGroup(structureGroup);clearGroup(roadGroup);clearGroup(peopleGroup);blockViews=new Map();markers=[];markerLayer.replaceChildren();agents=[];cars=[];inspectId=null;$('#inspect').hidden=true;eventList=[];for(const b of town.blocks){redrawBlock(b);if(stage(b,town.time)>=3&&b.type==='home')makeResidents(b);}rebuildRoads();event(town.blocks.length?'保存した街を開きました。':'この土地から、小さな街がはじまります。');$('#welcome').hidden=town.blocks.length>0;selectMode('explore');setSpeed(1);lastSimMinute=-1;target.set(0,0,0);zoom=DEFAULT_ZOOM;angle=Math.PI/4;updateCamera();updateHUD();}
const touches=new Map();let pinch=null;
renderer.domElement.addEventListener('pointerdown',e=>{world.focus({preventScroll:true});renderer.domElement.setPointerCapture(e.pointerId);touches.set(e.pointerId,[e.clientX,e.clientY]);if(touches.size===2){const t=[...touches.values()];pinch={distance:Math.hypot(t[0][0]-t[1][0],t[0][1]-t[1][1]),zoom};drag=null;clearGroup(previewGroup);return;}
 drag={start:plotAt(e),last:plotAt(e),x:e.clientX,y:e.clientY,target:target.clone(),pan:mode==='explore'||e.button===2||e.button===1,moved:false};if(!drag.pan&&drag.start)preview([drag.start]);});
renderer.domElement.addEventListener('pointermove',e=>{if(touches.has(e.pointerId))touches.set(e.pointerId,[e.clientX,e.clientY]);if(pinch&&touches.size===2){const t=[...touches.values()];zoom=THREE.MathUtils.clamp(pinch.zoom*Math.hypot(t[0][0]-t[1][0],t[0][1]-t[1][1])/pinch.distance,.45,3.6);updateCamera();return;}
 if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||=Math.hypot(dx,dy)>5;if(drag.pan){const scale=48/zoom/innerHeight;target.copy(drag.target);target.x+=(-dx*Math.cos(angle)-dy*Math.sin(angle)*1.5)*scale;target.z+=(dx*Math.sin(angle)-dy*Math.cos(angle)*1.5)*scale;target.x=THREE.MathUtils.clamp(target.x,-25,25);target.z=THREE.MathUtils.clamp(target.z,-25,25);updateCamera();}else{const p=plotAt(e);if(p&&drag.start){drag.last=p;preview(dragPlots(drag.start,p));}}}else{const p=plotAt(e);if(mode!=='explore'){if(p)preview([p]);else clearGroup(previewGroup);}else if(p){const b=blockForPlot(p);if(b){const idx=b.plots.findIndex(q=>q[0]===p[0]&&q[1]===p[1]);const hoverKey=b.id+'-'+idx;if(hoverPlot!==hoverKey){hoverPlot=hoverKey;showInspect(b.id,idx);}}}}});
function pointerEnd(e){touches.delete(e.pointerId);if(pinch){if(touches.size<2)pinch=null;drag=null;return;}if(!drag)return;const d=drag;drag=null;if(!d.pan&&d.start&&d.last)addPlots(mode,dragPlots(d.start,d.last));else if(d.pan&&!d.moved){const p=plotAt(e),b=p&&blockForPlot(p);if(b)showInspect(b.id,b.plots.findIndex(q=>q[0]===p[0]&&q[1]===p[1]));else{$('#inspect').hidden=true;inspectId=null;}}clearGroup(previewGroup);}
renderer.domElement.addEventListener('pointerup',pointerEnd);renderer.domElement.addEventListener('pointercancel',e=>{touches.delete(e.pointerId);drag=null;pinch=null;clearGroup(previewGroup);});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=THREE.MathUtils.clamp(zoom*Math.exp(-e.deltaY*.001),.45,3.6);updateCamera();},{passive:false});
$$('[data-zone]').forEach(b=>b.onclick=()=>selectMode(b.dataset.zone));$$('[data-speed]').forEach(b=>b.onclick=()=>setSpeed(Number(b.dataset.speed)));
$('#begin').onclick=()=>{selectMode('home');$('#welcome').hidden=true;toast('住宅を置く場所を選んでね');};$('#close-inspect').onclick=()=>{inspectId=null;$('#inspect').hidden=true;hoverPlot=null;};
$('#zoom-in').onclick=()=>{zoom=Math.min(3.6,zoom*1.2);updateCamera();};$('#zoom-out').onclick=()=>{zoom=Math.max(.45,zoom/1.2);updateCamera();};$('#rotate').onclick=()=>{angle+=Math.PI/2;updateCamera();};$('#camera-home').onclick=()=>{target.set(0,0,0);zoom=DEFAULT_ZOOM;angle=Math.PI/4;updateCamera();};$('#help').onclick=()=>{$('#welcome').hidden=!$('#welcome').hidden;};
const SAVE_KEY='okemon-minitown-v1';function updateLoad(){try{$('#load').disabled=!localStorage.getItem(SAVE_KEY);}catch{$('#load').disabled=true;}}
$('#save').onclick=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(town));updateLoad();toast('このブラウザに街を保存しました');}catch{toast('保存できませんでした。ブラウザの保存設定を確認してください');}};
$('#load').onclick=()=>{try{const t=parseSave(localStorage.getItem(SAVE_KEY));reset(t);history.replaceState(null,'',location.pathname);toast('保存した街を開きました');}catch{toast('保存した街を読み込めませんでした');}};
$('#new').onclick=()=>$('#new-dialog').showModal();$('#cancel-new').onclick=()=>$('#new-dialog').close();$('#confirm-new').onclick=()=>{$('#new-dialog').close();reset();history.replaceState(null,'',location.pathname);};
window.addEventListener('keydown',e=>{if($('#new-dialog').open)return;if(e.target.matches('input,textarea,select'))return;const k=e.key.toLowerCase();const modes={v:'explore','1':'home','2':'shop','3':'work','4':'park'};if(modes[k])selectMode(modes[k]);if(e.code==='Space'){e.preventDefault();setSpeed(speed===0?previousSpeed:0);}if(k==='q'||k==='e'){angle+=(k==='q'?-1:1)*Math.PI/2;updateCamera();}if(k==='escape'){$('#welcome').hidden=true;$('#inspect').hidden=true;selectMode('explore');}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const dx=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0,dz=e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0;target.x+=dx*Math.cos(angle)+dz*Math.sin(angle);target.z+=-dx*Math.sin(angle)+dz*Math.cos(angle);updateCamera();}});
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);if(scenic)sceneCamera();else updateCamera();});
window.addEventListener('error',()=>{$('#error').hidden=false;});
function sceneCamera(){if(study){target.set(-4.65,0,commute?-2.5:-.65);angle=Math.PI/4;zoom=innerWidth<760?Math.min(2.3,innerWidth/innerHeight*(commute?2.1:3.1)):(commute?1.65:2.98);updateCamera();return;}target.set(0,0,1.2);angle=Math.PI/4;zoom=innerWidth<760?Math.min(1.1,innerWidth/innerHeight*1.45):1.82;updateCamera();}
function viewTown(){reset(study?(new URLSearchParams(location.search).get('scene')==='commute'?commuteTown():referenceTown(new URLSearchParams(location.search).get('growth')==='full')):komorebiTown());scenic=true;grid.visible=plotGrid.visible=false;document.body.classList.add('scenic');$('#town-view').hidden=false;$('#welcome').hidden=true;sceneCamera();eventList=[];$('#events').innerHTML='';schedules();for(let i=0;i<15;i++)moveAgents(.2);updateHUD();setViewChrome(true);$$('[data-hour]').forEach(el=>el.setAttribute('aria-pressed',el.dataset.hour==='21'));document.title=study?(commute?'MiniTown｜出勤の朝':'MiniTown｜住宅3軒の再現比較'):'こもれびの街｜MiniTown';if(study){setViewChrome(false);grid.visible=plotGrid.visible=true;grid.material.opacity=.025;plotGrid.material.opacity=.025;setSpeed(0);$('#town-view').hidden=true;document.body.classList.add('reference-study');event(new URLSearchParams(location.search).get('scene')==='commute'?'朝7:50。▶で進めると10人が仕事場へ向かいます。':`住宅3軒・${agents.length}人の比較用の街を開きました。`);}}
$$('[data-hour]').forEach(b=>b.onclick=()=>{const hour=Number(b.dataset.hour);const nextTime=Math.floor(town.time/1440)*1440+hour*60;const delta=nextTime-town.time;for(const block of town.blocks)block.born+=delta;town.time=nextTime;for(const a of agents)if(a.route){a.current=a.destination;a.currentPlot=a.destinationPlot;a.route=null;a.mesh.visible=false;}schedules();$$('[data-hour]').forEach(el=>el.setAttribute('aria-pressed',el===b));updateHUD();});
function setViewChrome(hide){document.body.classList.toggle('hide-chrome',hide);$$('.hud,.bottom,.right-tools,#inspect').forEach(el=>el.inert=hide);$('#view-chrome').textContent=hide?'操作を表示':'景色だけを見る';$('#view-chrome').setAttribute('aria-pressed',hide);}
$('#view-chrome').onclick=()=>setViewChrome(!document.body.classList.contains('hide-chrome'));
$('#camera-home').onclick=()=>{if(scenic)sceneCamera();else{target.set(0,0,0);zoom=DEFAULT_ZOOM;angle=Math.PI/4;updateCamera();}};
if(study||new URLSearchParams(location.search).get('town')==='komorebi')viewTown();else reset();updateLoad();requestAnimationFrame(renderTick);
