import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const checks = [];
const check = (name, success) => checks.push({ name, pass: Boolean(success) });
const html = read('index.html'), app = read('app.mjs'), renderer = read('renderer.mjs'), css = read('style.css');
for (const file of ['app.mjs', 'renderer.mjs', 'model.mjs', 'making.mjs']) check(`syntax: ${file}`, spawnSync(process.execPath, ['--check', path.join(root, file)]).status === 0);
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
check('all HTML IDs are unique', new Set(ids).size === ids.length);
check('all literal JS element lookups have an HTML target', [...app.matchAll(/\$\('#([^']+)'\)/g)].every(m => ids.includes(m[1])));
check('local HTML assets resolve', [...html.matchAll(/(?:src|href)="([^"#]+)"/g)].filter(m => !m[1].startsWith('http')).every(m => fs.existsSync(path.join(root, m[1]))));
check('no network, HTML injection or evaluation in app/renderer', !/\bfetch\s*\(|XMLHttpRequest|innerHTML|outerHTML|\beval\s*\(/.test(app + renderer));
check('PNG uses the same renderer state and visible canvas', app.includes('renderer.render(state);') && app.includes("canvas.toBlob(value =>") && app.includes("'image/png'"));
check('object URLs are revoked when replaced', app.includes('if (downloadURL) URL.revokeObjectURL(downloadURL);'));
check('zero-sized pointer bounds are guarded', app.includes('if (rect.width <= 0 || rect.height <= 0) return;'));
check('font readiness precedes first renderer creation', app.indexOf('await document.fonts.ready') < app.indexOf('renderer = new EmbossRenderer'));
check('no elapsed-time or autonomous animation', !/performance\.now|setInterval|Date\.now/.test(app + renderer));
check('pointer cancellation and keyboard support', app.includes('pointercancel') && app.includes('lostpointercapture') && app.includes("event.key === 'Home'"));
check('IME composition is explicitly guarded', app.includes("compositionstart") && app.includes("compositionend") && app.includes('if (composing) return;'));
check('mobile and reduced-motion CSS exist', css.includes('@media(max-width:780px)') && css.includes('prefers-reduced-motion'));
check('process, brief and making guide exist', ['PROCESS.md', 'prompts/build-brief.md', 'making.html', 'README.md'].every(f => fs.existsSync(path.join(root, f))));
const report = { checkedAt: new Date().toISOString(), scope: 'static and syntax only; browser acceptance is separate', passed: checks.filter(c => c.pass).length, total: checks.length, checks };
fs.writeFileSync(path.join(root, 'qa/static-report.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report, null, 2));
if (checks.some(c => !c.pass)) process.exitCode = 1;
